config/routes.rb
require 'sidekiq/web'

Dating::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'edit' => 'users#edit'
  get "/profile/:id" => "users#show"
  get "profile/:id/settings" => 'users#edit'
  get 'settings/:id' => 'users#settings'
  get 'admin/users' => 'admin#users'
  get 'admin/subscriptions' => 'admin#subscriptions'
  get 'admin/letsgo' => 'admin#letsgo'
  get 'admin/messages' => 'admin#messages'
  get 'admin/qanda' => 'admin#qanda'
  get 'admin/pictures' => 'admin#pictures'
  get 'letsgos/eatdrink' => 'letsgos#eatdrink'
  get 'letsgos/listenwatch' => 'letsgos#listenwatch'
  get 'letsgos/play' => 'letsgos#play'
  get 'letsgos/other' => 'letsgos#other'
  get 'letsgos/explore' => 'letsgos#explore'
  get "subscriptions/cancelsubscription"
  get "subscriptions/updatesubscription"
  get "subscriptions/changecard"
  get "subscriptions/suspend"
  get "subscriptions/updatebilling"
  get "subscriptions/reactivate"
  get ":id/updatebilling" => "users#update_stripe_billing"
  match '/edit_card',   to: 'subscriptions#edit_card',   via: 'get'
  match '/update_card', to: 'subscriptions#update_card', via: 'post'
  get '/relationships/set_follow' => 'relationships#set_follow'
  get '/speed_dates' => 'users#speed_date'
  
  post 'subscription_event' => "webhooks#subscription_event"
  

    
    resources :messages do
      member do
      post :askout
      end
    end

      
  match '/paypal/ipn' => 'notifications#create', :via => [:get, :post], :as => 'notifications_create'
  
  resources :admin
  resources :charges
  resources :subscriptions
  resources :plans
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  get 'paypal/subscription', to: 'subscriptions#paypal_subscription_record', :as => 'paypal_subscription_create'
 
  resources :sessions
  resources :contacts, only: [:new, :create]
  resources :password_resets
  resources :galleries
  resources :photos do
    member do
      post :avatar
    end
  end
  resources :searches do
	get 'save_searches', on: :collection
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :letsgos, only: [:create, :destroy]
  resources :users do  
    get 'settings', on: :member  
    post 'follow', on: :member 
    post 'unfollow', on: :member
    get "follow", on: :member 
    get 'follow_popup', on: :member
    post :search, on: :collection
  end
  
  resources :letsgos do
    member do
      post :repost
      post :interested
    end
  end
  
  resources :questions do
    resources :answers, only: [:new, :create]
  end

          
  root to: 'users#index'
  
  resources :users do
  end
 
 resources :conversations do
     post :reply, on: :member
     post :trash_all, on: :collection
     post :untrash, on: :collection
   end

  resources :payments, only: [:show, :create, :destroy] do
     collection do
       get :success
       get :cancel
       post :notify
     end     
   end
   

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def new
    @question = Question.find(params[:question_id])
  end
  
  def show
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end
  
  def create
    @question = Question.find(params[:question_id])
    if @question.update_attributes(params[:question])
      conversation = @question.conversation
      conversation.move_to_trash(current_user)
      redirect_to conversations_path
    else
      render :new
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class = "answers-block">
	<%= simple_format(question.answer) %>
	<p>
		<small><%= answer.user_name %> - <%= time_ago_in_words(answer.created_at) %></small>
		</p>
		</div>

app/views/answers/_form.html.erb
<p class="flash"><%= flash[:notice] %></p>

<%= form_for(:question, :url => question_answers_path(question)) do |f| %>
	<div class='form_container' style='width: 100%;border: 0 none;'>
		<ul style='list-style: none;'>
			<li><%= f.text_area :answer, {:placeholder => 'Write your answer here...' , :style=>'width:97%;height:50px;resize: none; border: 1px solid #AAA; padding: 10px; margin-bottom: 10px;'} %></li>
			<li><%= hidden_field_tag :recipient_id, {:placeholder => 'Please add your name...' , :style=>'width:97%;border: 1px solid #AAA; padding: 10px; margin-bottom: 10px;'}  %></li>
			<li><%= f.submit "Respond", :class => 'find_btn', :style=>'margin:0' %></li>
			</ul>
			<% end %>

app/views/answers/_show.html.erb
	<%= @question%>